version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/usr/app
    ports:
      - 8000:80

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080
